### ISSUE TITLE
About the problem that error occurs in MarkDrip

### ISSUE THREAD

**Issue by Comamoca** [Comamoca/MarkDrip#1]
## Summary of the problem

```
README.md output.html github
Traceback (most recent call last):
  File "/home/coma/.local/bin/markdrip", line 8, in <module>
    sys.exit(main())
  File "/home/coma/.local/pipx/venvs/markdrip/lib/python3.10/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/coma/.local/pipx/venvs/markdrip/lib/python3.10/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/coma/.local/pipx/venvs/markdrip/lib/python3.10/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/coma/.local/pipx/venvs/markdrip/lib/python3.10/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/coma/.local/pipx/venvs/markdrip/lib/python3.10/site-packages/markdrip/main.py", line 12, in main
    mkup, filename = gen.markup(target)
  File "/home/coma/.local/pipx/venvs/markdrip/lib/python3.10/site-packages/markdrip/mods/generator.py", line 14, in markup
    with open(filepath) as f:
FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
```
## Possible causes
The path to read the extended CSS of MarkDrip is incorrect.

**Comment by Comamoca** [comment]
Fixed in version `0.1.4`!

 Do `pip install -U markdrip` to update!
